server:
  port: 8081

iso:
  default-nr: 13
  default-seq-nr: "001"
  last-upd-user: sp
  de39-success: "00"
  de39-failed: "01"

limit:
  max-21: "999999999999999999999999"
  max-12: "999999999999"
  prefix-1: "1242292125228510"
  prefix-2: "1241292125328510"
  prefix-3: "1242292125228510"
  default-value: "0"
  default-profile-nr: 42
  default-rule-nr: 52

spring:
  application:
    name: iso-parser

  datasource:
    url: jdbc:postgresql://localhost:5432/isodb
    username: postgres
    password: root

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
